### ISSUE TITLE
Fix margins of documentation site sidebar

### ISSUE THREAD

**Issue by edgarmueller** [eneufeld/jsonforms-website#5]
The margins of the sidebar (the grey one) seem to be small. Hence, the margin of the items in the sidebar should be increased.

**Comment by edgarmueller** [comment]
I'd probably also increase the right margin of the main content section since it spans over the whole screen and therefore is a little  bit hard to read, but this is just my opinion.

**Comment by eneufeld** [comment]
Should be fixed now
